/// Flutter icons My_day_icon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  My_day_icon
///      fonts:
///       - asset: fonts/My_day_icon.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class MyDayIcon {
  MyDayIcon._();

  static const _kFontFam = 'MyDayIcon';

  static const IconData home = IconData(0xe901, fontFamily: _kFontFam);
  static const IconData group = IconData(0xe900, fontFamily: _kFontFam);
  static const IconData temporary_group = IconData(0xe903, fontFamily: _kFontFam);
  static const IconData study = IconData(0xe902, fontFamily: _kFontFam);
}
